spring:
  datasource:
    name: Demo
    password: root
    url: jdbc:mysql://localhost:3306/sales
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 265147779200-nl0iuqhb1diq43b8g76ggsu3okaqg4q2.apps.googleusercontent.com
          clientSecret: VfqlslJufOe1HEWGonZ3V1V0
          scope:
           - email
           - profile

